version: "3"

services:
  app:
    build:
      context: .
    networks:
      - demo_net
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/demo
      - /usr/src/demo/node_modules
    depends_on:
      - db
    tty: true
    container_name: demo_app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: demo_db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=onmdb
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=root
    networks:
      - demo_net
    ports:
      - "3306:3306"

networks:
  demo_net:
    driver: bridge
